[settings]
idiomatic_version_file_enable_tools = ["python"]

[tools]
uv = "latest"

[tasks.install]
description = "Install dependencies"
depends = ["python-install", "ansible-install"]

[tasks.python-install]
description = "Install Python packages"
run = "uv sync --frozen"
sources = ["mise.toml", "pyproject.toml", "uv.lock"]

[tasks.ansible-install]
description = "Install Ansible collections"
depends = ["python-install"]
run = "uv run ansible-galaxy collection install -r requirements.yml"
sources = ["mise.toml", "requirements.yml"]
