[settings]
idiomatic_version_file_enable_tools = ["python"]

[tasks.install]
description = "Install dependencies"
depends = ["pip-install"]

[tasks.pip-install]
description = "Install Python packages"
run = "pip install -r requirements.txt"
sources = ["mise.toml", "requirements.txt"]
