[settings]
idiomatic_version_file_enable_tools = ["python"]

[tasks.install]
description = "Install dependencies"
depends = ["pip-install", "ansible-install"]

[tasks.pip-install]
description = "Install Python packages"
run = "pip install -r requirements.txt"
sources = ["mise.toml", "requirements.txt"]

[tasks.ansible-install]
description = "Install Ansible collections"
depends = ["pip-install"]
run = "ansible-galaxy collection install -r requirements.yml"
sources = ["mise.toml", "requirements.yml"]
