---
- name: Install base packages
  ansible.builtin.apt:
    name:
      - cluster-glue
      - corosync
      - crmsh
      - pacemaker
      - pcs
    update_cache: true

- name: Install fence-agents and resource-agents (legacy)
  when: >
    (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version | int < 22) or
    (ansible_distribution == 'Debian' and ansible_distribution_major_version | int <= 12)
  ansible.builtin.apt:
    name:
      - fence-agents
      - resource-agents

- name: Install fence-agents-base and resource-agents-base (>= Ubuntu 22)
  when: >
    ansible_distribution == 'Ubuntu' and ansible_distribution_major_version | int >= 22
  ansible.builtin.apt:
    name:
      - fence-agents-base
      - resource-agents-base

- name: Install fence-agents-all and resource-agents (Debian 13+)
  when: >
    ansible_distribution == 'Debian' and ansible_distribution_major_version | int >= 13
  ansible.builtin.apt:
    name:
      - fence-agents-all
      - resource-agents

- name: Looking for existing {{ corosync_authkey_file }}
  ansible.builtin.stat:
    path: "{{ corosync_authkey_file }}"
  register: _corosync_authkey

- name: Generating corosync authkey
  when:
    - not _corosync_authkey['stat']['exists']
    - inventory_hostname == pacemaker_primary_server
  block:
    - name: Installing haveged on {{ pacemaker_primary_server }}
      ansible.builtin.apt:
        name: haveged
        state: present

    - name: Generating corosync authkey on {{ pacemaker_primary_server }}
      register: _corosync_keygen
      changed_when: _corosync_keygen.rc == 0
      failed_when: _corosync_keygen.rc != 0
      ansible.builtin.command: corosync-keygen

    - name: Removing haveged from {{ pacemaker_primary_server }}
      ansible.builtin.apt:
        name: haveged
        purge: true
        state: absent
