---
- name: Determine primary node
  ansible.builtin.import_tasks: cluster/determine_primary_node.yml

- name: Install components
  ansible.builtin.import_tasks: install.yml

- name: Configure corosync
  ansible.builtin.import_tasks: config.yml

- name: Configure cluster
  ansible.builtin.import_tasks: cluster.yml
