---
- name: determine primary node
  ansible.builtin.import_tasks: cluster/determine_primary_node.yml

- name: restart resource
  when: inventory_hostname == pacemaker_primary_server
  any_errors_fatal: true
  block:
    - name: fetch resource config
      ansible.builtin.set_fact:
        _resource: "{{ pacemaker_cluster_resources | selectattr('resource_id', 'equalto', resource_name) }}"

    - name: process with resource config
      when: _resource | length
      block:
        - name: get resource config
          ansible.builtin.set_fact:
            _resource: "{{ _resource | first }}"

        - name: run test command before restart
          ansible.builtin.command: "{{ _resource.test_command }}"
          when: _resource.test_command is defined

        - name: cleanup resource status for {{ resource_name }}
          ansible.builtin.command: pcs resource cleanup {{ _resource.resource_id }}
          tags:
            - always
          changed_when: false

        - name: restart resource {{ resource_name }}
          when: not ansible_check_mode
          ansible.builtin.command: pcs resource restart {{ _resource.resource_id }}
          retries: 5
          delay: 5
          register: result
          until: result.rc == 0
          tags:
            - always
