---
- name: Fetch node name from resource status
  changed_when: false
  register: _recource_node
  failed_when: false
  args:
    executable: /bin/bash
  ansible.builtin.shell: |
    set -o pipefail
    pcs resource show | head -n1 | rev | cut -d ' ' -f1 | rev

- name: Update primary server variabel
  when:
    - not ansible_check_mode
    - _recource_node.rc == 0
    - _recource_node.stdout in hostvars.keys()
  changed_when: false
  ansible.builtin.set_fact:
    pacemaker_primary_server: "{{ _recource_node.stdout }}"

- name: Show primary node value
  ansible.builtin.debug:
    msg: "{{ pacemaker_primary_server }}"
