---
- name: Try to fetch pcs version
  register: _pcs_version
  changed_when: false
  failed_when: false
  check_mode: false
  ansible.builtin.command: pcs --version

- name: Try to fetch node name from resource status
  check_mode: false
  when: _pcs_version.rc == 0
  block:
    - name: Fetch node name from resource status
      changed_when: false
      register: _recource_node
      failed_when: false
      args:
        executable: /bin/bash
      ansible.builtin.shell: |
        set -o pipefail
        pcs resource {{'show' if _pcs_version.stdout is version('0.10.0', '<') else 'status'}} \
          | head -n1 | rev | cut -d ' ' -f1 | rev

    - name: Update primary server variabel
      when:
        - _recource_node.rc == 0
        - _recource_node.stdout in hostvars.keys()
      changed_when: false
      ansible.builtin.set_fact:
        pacemaker_primary_server: "{{ _recource_node.stdout }}"

- name: Show primary node value
  ansible.builtin.debug:
    msg: "{{ pacemaker_primary_server }}"
