---
- name: Restart corosync
  ansible.builtin.service:
    name: corosync
    state: restarted

- name: Restart pacemaker
  ansible.builtin.service:
    name: pacemaker
    sleep: 10
    state: restarted
