---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: node1
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    command: "/lib/systemd/systemd"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true

  - name: node2
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    command: "/lib/systemd/systemd"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
scenario:
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - destroy
