---
- name: Verify
  hosts: all
  become: true
  tasks:
    - name: Check Pacemaker service is enabled and running
      register: pacemaker_service
      ansible.builtin.systemd:
        name: pacemaker

    - name: Assert Pacemaker service is active and running
      ansible.builtin.assert:
        that:
          - pacemaker_service.status.ActiveState == "active"
          - pacemaker_service.status.SubState == "running"
