---
- name: capturing cluster property
  ansible.builtin.command: pcs property show {{ cluster_property.name }}
  register: _pcs_property_show
  changed_when: false
  failed_when: false

- name: ensure cluster property is set
  when:
    - cluster_property.state | default('present') | lower == 'present'
    - "(' ' ~ cluster_property.name ~ ': ' ~ cluster_property.value) not in _pcs_property_show.stdout"
  ansible.builtin.command: pcs property set {{ cluster_property.name }}={{ cluster_property.value | default('') }}

- name: ensure cluster property is not set
  when:
    - cluster_property.state | default('present') | lower == 'absent'
    - "(' ' ~ cluster_property.name ~ ': ' ~ cluster_property.value) in _pcs_property_show.stdout"
  ansible.builtin.command: pcs property unset {{ cluster_property.name }}
