name: CI

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint Ansible Role
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version-file: .python-version
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint Ansible files with ansible-lint
        run: ansible-lint

  test:
    name: Test Ansible Role
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - debian12
          - debian13
          - ubuntu2204
          - ubuntu2404
          - ubuntu2604
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version-file: .python-version
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Cache Ansible collections
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.ansible/collections
          key: ${{ runner.os }}-ansible-deps-${{ hashFiles('requirements.yml') }}
          restore-keys: |
            ${{ runner.os }}-ansible-deps-

      - name: Install Ansible collections
        run: ansible-galaxy collection install -r requirements.yml

      - name: Run Molecule tests
        env:
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ${{ matrix.distro }}
        run: molecule test
