name: Publish

on:
  push:
    tags:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish Ansible Role
    runs-on: ubuntu-latest

    steps:
      - name: Publish
        uses: skriptfabrik/github-actions/import-ansible-galaxy-role@main
        with:
          api-key: ${{ secrets.GALAXY_API_KEY }}
